import type { Metadata } from "next";
import { Commissioner, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "@/components/theme-provider"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  display: "swap",
})

export const metadata: Metadata = {
  title: "AI Tech Talk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en" suppressHydrationWarning className="overflow-auto mt-10">
      <body
        className={`${inter.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="fixed top-0 left-0 right-0 z-10 flex items-center justify-between p-4 shadow-md bg-opacity-40 backdrop-blur-lg">
          <div className="flex items-center">
            <Link href="/" className="flex items-center space-x-2">
              <h1 className="text-2xl font-bold text-gray-800">
                AI Tech Talk
              </h1>
            </Link>
          </div>
          <div className="flex items-center space-x-8 pr-4">
            <Link href="/" className="text-gray-800 hover:text-blue-500">
              Home
            </Link>
            <Link href="/chat-window" className="text-gray-800 hover:text-blue-500">
              Chat
            </Link>
            <Link href="/generative-ui" className="text-gray-800 hover:text-blue-500">
              Gen UI
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
